//
//  Event.h
//  Neon21
//
//  (c) Neon Games LLC, 2012.

typedef enum
{
    EVENT_EMPTY = 0,
    EVENT_ANY_BUTTON_UP,
    EVENT_ANY_BUTTON_DOWN,
    EVENT_APPLICATION_SUSPENDED,
    EVENT_APPLICATION_RESUMED,
    EVENT_APPLICATION_WILL_TERMINATE,
    EVENT_APPLICATION_ENTERED_BACKGROUND,
    EVENT_APPLICATION_ENTERED_FOREGROUND,
    
    EVENT_CRYSTAL_ITEM_SPAWN,
    EVENT_CRYSTAL_ITEM_NOT_TAPPED,
    EVENT_CRYSTAL_ITEM_TAPPED,
    EVENT_CRYSTAL_ITEM_EXPIRED,
    EVENT_CRYSTAL_ITEM_AUTO_EXPIRED,
    
    EVENT_INIT_GL_CONTEXT_CREATED,
    EVENT_POWERUPS_AWARDED,
	EVENT_CONCLUSION_BROKETHEBANK,
	EVENT_TUTORIAL_COMPLETED,
	EVENT_TUTORIAL_DIALOGUE,
    EVENT_STINGER_CREATED,
    EVENT_STINGER_DISMISSED,
    EVENT_STINGER_EXPIRED,
    EVENT_STATE_STARTED,
    EVENT_STATE_RESUMED,
    EVENT_HINT_TRIGGERED,
    EVENT_MAIN_MENU_PENDING_TERMINATE,
    EVENT_MAIN_MENU_ACTIVATE_VIP,
    EVENT_MAIN_MENU_LEAVE_MENU,
    EVENT_MAIN_MENU_ENTER_LEVEL_SELECT,
    EVENT_MAIN_MENU_LEVEL_SELECT_PENDING,
    EVENT_INCREMENTAL_GAME_ADD_POWERUP,
    EVENT_MUSIC_ENABLED,
    EVENT_LIGHT_REMOVED,
    EVENT_NEON21_HANDOVER,
    EVENT_PHYSICS_COLLISION,
    EVENT_RATED_GAME,
    EVENT_RUN21_PENDING_TERMINATE,
    EVENT_USE_POWERUP,
    EVENT_OPEN_STORE,
	EVENT_DEBUG_SKIPSTATE,
    EVENT_IAP_DELIVER_CONTENT,
    EVENT_IAP_PRICES_RECEIVED,
    EVENT_INCREMENTAL_GAME_START,
    EVENT_INCREMENTAL_GAME_ITEM_CLICKED,
    EVENT_INCREMENTAL_GAME_POWERUP_PURCHASED,
    EVENT_INCREMENTAL_GAME_UNLOCK_STATE_CHANGED,
    EVENT_TUTORIAL_EVALUATE_PHASE
} EventId;